// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UsersSearchController from "./users_search_controller"
application.register("users-search", UsersSearchController)

import PlaceSearchController from "./place_search_controller"
application.register("place-search", PlaceSearchController)

import PostsSearchController from "./posts_search_controller"
application.register("posts-search", PostsSearchController)

import LeadsSearchController from "./leads_search_controller"
application.register("leads-search", LeadsSearchController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import CompanySearchController from "./company_search_controller"
application.register("company-search", CompanySearchController)
