// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import GlobalSearchController from "./global_search_controller"
Stimulus.register("global-search", GlobalSearchController)

import PlaceSearchController from "./place_search_controller"
Stimulus.register("place-search", PlaceSearchController)